version: "3.8"

services:
  spring:
    build: .
    container_name: spring_managing
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://host.docker.internal:3306/managing"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "0806"
    ports:
      - "8090:8090"
